[package]
name = "xilem_spotify"
version = "0.1.0"
edition = "2024"

[dependencies]
librespot-core = "0.7.1"
librespot-oauth = "0.7.1"
librespot-playback = "0.7.1"
librespot-metadata = "0.7.1"
xilem = { git="https://github.com/linebender/xilem"}
rspotify = "0.15.1"
chrono = "0.4.42"
