[package]
name = "taan"
version = "0.1.0"
edition = "2024"

[dependencies]
librespot-core = "0.7.1"
librespot-oauth = "0.7.1"
librespot-playback = "0.7.1"
librespot-metadata = "0.7.1"
rspotify = "0.15.1"
chrono = "0.4.42"
slint = "1.13.1"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
slint-build = "1.13.1"
